### ISSUE TITLE
update dependency

### ISSUE THREAD

**Issue by Arhell** [luyadev/luya.io#8]
vitepress  ^1.0.0-alpha.30  →  ^1.0.0-alpha.32

**Comment by nadar** [comment]
I have no configured depandbot for this task :-) as this can be done automatically https://github.com/luyadev/luya.io/commit/cbb84ee04f3ad03f933c83e125f3098e95bc8e28

**Comment by nadar** [comment]
https://github.com/luyadev/luya.io/pull/9
